service: first
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  environment: 
    MY_SECRET: ${file(./src/config/environments/env.${self:provider.stage}.json):CREDS}
plugins:
  - serverless-offline
functions:
  test:
    handler: src/app.server
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
          